# Site settings
title: YourKing's Blog
SEOTitle: 友钦的博客 | BenYourKing‘s Blog
header-img: img/post-bg-desk.jpg
email: yourking1982@gmail.com
description: "Every failure is leading towards success."
keyword: "YK, BenYourKing Blog, 友钦的博客, youqinwu, 吴友钦, python, question，data, pattern，mechanism，the law"
url: "http://iamyourking007.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/IamYourKing007/iamyourking007.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "If not me,who?If not now,when?"
sidebar-avatar: /img/yourkingself.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`


# SNS settings
RSS: false
#weibo_username:     
zhihu_username: wu-you-qin-33
github_username: IamYourKing007
#facebook_username: xxx
jianshu_username: c1e1ff6e7377
#twitter_username:   qiubaiying


# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
#每页显示的blog数目

permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`


# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: qiubaiying

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 17c4b282c4efdadc47a4                            #生成的clientID
  clientSecret: 522b9395c430cf8c27b0d4227508270a5541dff0    #生成的clientSecret
  repo: iamyourking007.github.io    #仓库名称
  owner: IamYourKing007    #github用户名
  admin: IamYourKing007
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
#ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
#ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
#ga_domain: qiubaiying.top               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "CCR",
        href: "https://computational-communication.com/"
    },{
        title: "Lingfei Wu",
        href: "https://lingfeiwu.github.io"
    },{
        title: "Chenjun Wang",
        href: "https://chengjunwang.com/"
    },{
        title: "Huimin Xu",
        href: "https://xuhuimin2017.github.io"
    }
    ,{
        title: "Haochuan Cui",
        href: "https://hashc.github.io/about/"
    }
    ,{
        title: "Yanbo Zhang",
        href: "https://www.yanbozhang.com/"
    }
    ,{
        title: "Xiaoshuang Jia",
        href: "https://xiaoshuangjia.github.io/"
    }
    ,{
        title: "Yiling Lin",
        href: "https://yilinglin010.github.io/joyful-world/"
    }
]
